
s = 'Swhq/(Sq\\NP)'
o = 'Swhq/(Sq/NP)'
sd = 'Swhq/(Sq/NP)/N'
od = 'Swhq/(Sq\\NP)/N'
ot = 'other'

whw_cat_dict = {
    "what 're you looking": o,
    'what is he doing': o,
    'what did you throw': o,
    "what 's Ricky": o,
    'what d you see': o,
    'what has Celia got': o,
    'what did you catch': o,
    'what did that come from': ot,
    "what 's the elephant doing": o,
    'what do you call that': ot,
    'what happened': s,
    'what does that say': o,
    'what did he play': o,
    'what are you doing': o,
    'what did he do': o,
    "what 's Catherine doing": o,
    'what else did we see': o,
    'what are that': o,
    'what is blood': o,
    "what 's wrong with this": ot,
    'what was wrong with him': ot,
    'what is a chest': o,
    'what shall I write': o,
    'what is the monkey eating': o,
    'what else did you have': od,
    'what size is it': od,
    'what does it do': o,
    "what 's an alligator": o,
    'what do you hear': o,
    'what shall we play': o,
    'what d you think': o,
    'what are they all about': ot,
    'what is this': o,
    'what did the doggie do': o,
    'what are these': o,
    'what d you do': o,
    'what does Cromer have': o,
    "what 's the word": o,
    'what did he say': o,
    'what did your grandmother get on': o,
    "what 's the fireman doing": o,
    'what is that turning': o,
    'what does an airplane say': o,
    'what shall we do': o,
    "what 's a chicken": o,
    "what 're you digging for": ot,
    "what wo n't break": o,
    "what 're they doing": o,
    'what is the nurse': o,
    'what is the house on': ot,
    "what 're you working on": ot,
    'what did he break': o,
    'what d you have': o,
    'what are you making': o,
    'what d you find': o,
    'what did you cook': o,
    'what is a game': o,
    'what do you mean': o,
    'what name is it': o,
    'what does an airplane do': o,
    "what 're you doing": o,
    'what am I': o,
    'what did you hurt': o,
    "what 's the bird doing": o,
    'what did you get': o,
    'what you doing': o,
    'what did you make': o,
    "what 's happening": o,
    'what does Daddy say': o,
    'what did Paul get': o,
    'what did the doggie write': o,
    'what did he climb': o,
    "what does n't move": o,
    "what 's a wedding": o,
    'what does the button do': o,
    'what was his name': o,
    "what 's your name": o,
    'what does the horse do': o,
    'what does he sell': o,
    'what do you want': o,
    'what color is this': o,
    'what else': ot,
    "what 's": ot,
    'what else d you want': od,
    "what 's an elbow": o,
    'what was that breaking': o,
    'what did you forget': o,
    'what did you break': o,
    'what does this mean': o,
    'what d you hear': o,
    'what are you brushing': o,
    'what did you write': o,
    'what did you bite': o,
    'what is it': o,
    "what 's a pepper": o,
    'what does it sound like': o,
    'what does Daddy do': o,
    'what will the lion say': o,
    'what did he see': o,
    'what did we call it': o,
    'what d you want': o,
    'what is your name': o,
    'what are you serving': o,
    'what do you need': o,
    'what else happened': sd,
    "what is this I 've got": ot,
    'what does the knife do': o,
    'what did happen': o,
    'what do we do': o,
    "what 're dreams": o,
    'what takes the car': o,
    'what are you blowing': o,
    "what 's wrong with it": o,
    'what is that': o,
    'what is the elephant doing': o,
    "what 're we having": o,
    "what 's his name": o,
    'what did you buy': o,
    'what does your Mommy teach': o,
    'what does the jeep do': o,
    'what can I have': o,
    "what 'd he do": o,
    'what is he making': o,
    'what d you call that': o,
    'what are those': o,
    'what does a windmill do': o,
    'what did you do': o,
    'what about over here': o,
    'what kind is that': o,
    'what else did you see': od,
    "what 's that": o,
    "what is that you 're using": o,
    'what did Mommy say': o,
    'what were their names': o,
    'what game is it': o,
    'what else did you do': od,
    "what 's he saying": o,
    "what 're they advertising": o,
    "what 're you saying": o,
    'what is it doing': o,
    "what 's her name": o,
    'what are you riding': o,
    "what 'd I say": o,
    "what 're you drinking": o,
    "what 's the trailer doing": o,
    'what did you hit': o,
    'what do you think': o,
    'what does that roll like': o,
    'what is a chess': o,
    'what does it mean': o,
    "what 's he doing": o,
    "what 's Bambi doing": o,
    'what are you saying': o,
    "what 's a short": o,
    'what was it': o,
    'what does it say': o,
    "what 're they saying": o,
    'what is the pencil': o,
    'what shall I use': o,
    'what can you say': o,
    'what does that spell': o,
    'what is that for': o,
    'what did they find': o,
    'what does a snail do': o,
    'what else is there': od,
    'what do seals eat': o,
    'what else do you see': od,
    'what does he say': o,
    'what was that': o,
    'what are you showing her': o,
    'what else d you sing': od,
    'what shall I give you': o,
    "what wo n't you eat": o,
    'what does he call you': o,
    'what d you mean': o,
    "what 's wrong with them": o,
    'what did Rusty do': o,
    'what did she tell you': o,
    'what did you see': o,
    'what does he have': o,
    'what are you drinking': o,
    "what 's this": o,
    'what is spray': o,
    'what is the horse killing': o,
    'what happens when you laugh': ot,
    'what game is that': o,
    'what are they': o,
    'what are the colors': o,
    'what did she ride in': ot,
    "what 's Urs doing": o,
    'what can he say': o,
    'what shall we sing': o,
    'what are you talking about': o,
    "what 's he looking at": o,
    'what are the rules': o,
    'what is today': o,
    'what else do you need': od,
    'what did you give us': o,
    'what did the carpenter say': o,
    'what are you checking': o,
    'what is he': o,
    'what puzzle is that': o,
    'what was it doing': o,
    'what else do we need': od,
    "what 's a genie": o,
    "what 're you making": o,
    'what is it saying': o,
    'what were they doing': o,
    'what are you drawing': o,
    'what did you take': o,
    'what are you': o,
    'what did the ball hit': o,
    'what did the puzzle say': o,
    'what d you need': o,
    'what are you catching': o,
    'what did you play': o,
    'what do you have': o,
    'what do I do': o,
    'what are you bringing': o,
    'what is Goldilocks doing': o,
    'what does this like': o,
    'what did you tell me': o,
    'what are you writing': o,
    'what fits': s,
    'what am I doing': o,
    'what color are yours': o,
    'what are you eating': o,
    "what is n't working": o,
    'what happens': s,
    "what 're you looking for": o,
    'what did you say': o,
    "what 's your paper": o,
    'what happens when you win': s,
    'what kind was it': o,
    'what is he saying': o,
    'what does he raise': o,
    'what hurt you': o,
    'what are you reading': o,
    'what should we say': o,
    'what is that called': o,
    'what color is it': o,
    'what does he mean': o,
    'what are cowboys doing': o,
    'what shall I do': o,
    'what do I want': o,
    'what do you see': o,
    'what will you write': o,
    'what did he have': o,
    'what did you did': o,
    'what did you ask me': o,
    'what do owls say': o,
    "what 's its name": o,
    'what is Urs having': o,
    'what do you say': o,
    'which one has the doghouse': sd,
    'which one is blue': sd,
    'which finger': sd,
    'well which one is it': od,
    'which one would you like': od,
    'which book': sd,
    'which doggie': sd,
    'which color d you like': od,
    'which one d you want': od,
    "which part don 't you like": od,
    'which one would you like': od,
    'which germs': sd,
    'which one is Mr Walter': od,
    'which hand': sd,
    'which bench': sd,
    'which one': sd,
    'which one is like this': od,
    'which wheel': sd,
    'which one': sd,
    'which one did you choose': od,
    'which one is yellow': sd,
    'who fixes shoes': o,
    'he who': ot,
    "who 's reading the mail": s,
    'who reads his mail': s,
    'who wrote that': s,
    'who else do you see': od,
    "who 's the baby": o,
    'who else': s,
    'who can wear it': s,
    'who are you': o,
    'who is Michael': o,
    'Jack sees who': o,
    'who was laughing': s,
    "who 's crying": s,
    'who took them': s,
    'who found it': s,
    "who 's Michael": s,
    'who has a moustache': s,
    'who is he': o,
    'who is it': o,
    'who is driving': s,
    'who took it': s,
    "who 's that": o,
    'who are you asking': o,
    'who else does': s,
    'who is honey': s,
    'the salesman who breaks dolls': ot,
    'who made it': s,
    'who says meow': s,
    'who brought that': s,
    'who bakes pies': s,
    "it 's Rusty who has fingers": ot,
    'who opened it': s,
    "who 's talking": s,
    'you hit who': o,
    'who does': s,
    'who bit your pants': s,
    'who is Joey': o,
    'who did that': s,
    'who is this': o,
    "who 's been fighting you": s,
    'who is that': o,
    'who lost their mittens': s,
}

#test_whq_sents = ['what d you see', "what 's her name", "what 's your name", 'what does that say', 'what are you doing', 'what did he do', 'what d you need', 'what color is this', "what 's he doing", 'what was it', 'what does it say', 'what shall we play', 'what d you hear', 'what does that spell', 'what is it', 'what are you writing', 'what d you think', 'what are you eating', 'what does a snail do', 'what is this', 'what did you say', 'what are you serving', 'what are these', 'what else happened', 'what d you mean', 'what shall we do', "what 's this", 'what is that', 'what game is that', 'what does the jeep do', 'what shall I do', 'what did you buy', 'what d you have', 'what can he say', 'what are those', 'what did you do', 'what do owls say', 'what else do you need', 'what kind is that', "what 's that", "what 're you doing", 'what game is it', 'what else did you see', 'what did you get', 'what did you make', 'who is Michael', 'who is that', 'who are you', 'who says meow', 'which one']

#test_whw_cat_dict = {k:train_whw_cat_dict[k] for k in test_whq_sents}
